### ISSUE TITLE
Cannot run train.py without wandb account

### ISSUE THREAD

**Issue by benjamin-cates** [UCSD-E4E/acoustic-multiclass-training#10]
When starting train.py, a wandb account prompt is shown. If option 3 (continue without account) is entered, the program causes an error. Error on line 212 at `wandb.init()`.
![image](https://github.com/UCSD-E4E/acoustic-multiclass-training/assets/34255563/ca0d5d70-9ee4-492e-a714-82c850c35552)

**Comment by sprestrelski** [comment]
try `-l False` to turn logging off

**Comment by benjamin-cates** [comment]
Thank you that fixes it
