### ISSUE TITLE
Rework sweeps config to use yml

### ISSUE THREAD

**Issue by marco-bazzani** [UCSD-E4E/acoustic-multiclass-training#112]

**Comment by benjamin-cates** [comment]
Fixed in 92189336088d43e8eecc9dc74888da2742f084a5 in #103

**Comment by benjamin-cates** [comment]
Actually fixed in a1364bfde95013a4315add06ec1196225c5eb74b #117

**Comment by benjamin-cates** [comment]
Oops I misread the meaning of this issue, sorry about that
