### ISSUE TITLE
Chunking methods and documentation outdated for current pipeline

### ISSUE THREAD

**Issue by sprestrelski** [UCSD-E4E/acoustic-multiclass-training#27]
The new dataloader means that we no longer need to create 5-second chunks for training. Thus, chunking methods and their documentation should be updated to reflect this. I think it's a good idea to keep functionality to make these chunks since it's easier for PyTorch to load it in, but this should be de-emphasized.

**Comment by Sean1572** [comment]
Changes to documentation can be made in this pr

**Comment by benjamin-cates** [comment]
Resolved via pull request
