### ISSUE TITLE
Move augmentations from __getitem__ to __init__

### ISSUE THREAD

**Issue by marco-bazzani** [UCSD-E4E/acoustic-multiclass-training#61]

**Comment by Sean1572** [comment]
what do you imagine for this

**Comment by benjamin-cates** [comment]
I think he means the definitions of the transformations because right now they are being re inited every time 
![image](https://github.com/UCSD-E4E/acoustic-multiclass-training/assets/34255563/6d6023f5-87b4-48ee-a832-4d3c2c0f1282)

**Comment by benjamin-cates** [comment]
Also we should definitely have the probability be separated for each augmentation, honestly might as well define our own RandomApply at that point. And we need p to actually come from the config. Right now this is giving a 0.4 chance to apply both frequency masking and time masking when they should be independentish.

**Comment by marco-bazzani** [comment]
Working on that in sweep
