### ISSUE TITLE
Make bg noise alpha a range

### ISSUE THREAD

**Issue by marco-bazzani** [UCSD-E4E/acoustic-multiclass-training#71]

**Comment by mbazzani** [comment]
Fixed by [842ae34](https://github.com/UCSD-E4E/acoustic-multiclass-training/commit/842ae3410b41796021f51d80d1ab62898ef11337)

**Comment by marco-bazzani** [comment]
Fixed by [842ae34](https://github.com/UCSD-E4E/acoustic-multiclass-training/commit/842ae3410b41796021f51d80d1ab62898ef11337)
