### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by benjamin-cates** [UCSD-E4E/acoustic-multiclass-training#79]
There are two duplicated functions.

pad_audio is present in:
1. PyhaDFDataset self.pad_audio in `dataset.py:302`
2. utils.pad_audio in `utils.py:41`

crop_audio is present in:
1. PyhaDFDataset self.crop_audio in `dataset.py:310`
2. utils.crop_audio in `utils.py:49`

I personally think we should keep the versions in `utils.py`

**Comment by mbazzani** [comment]
Fixed by 0b3c4a7

**Comment by marco-bazzani** [comment]
Fixed by 0b3c4a7
